### ISSUE TITLE
Define how errors will be handled in the TIKI SDK

### ISSUE THREAD

**Issue by ricardobrg** [tiki/core-trail-endpoint#289]
As a developer, I need to have clear communication from the SDK to determine what caused the error, how to handle it, and how to prevent it in the future. 

The SDK relies on default errors, which can be confusing or even not passed to the SDK user when working with async methods. Therefore, we need to improve the error-handling mechanism in the TIKI SDK Dart.

### Tasks

- [ ] Define a standard error-catching behavior for the methods, including async. This can be either not catching the error, catching and throwing a custom error, catching and logging a message, or any other suitable method based on the type of error and use case.
- [ ] Define specific error codes/types and messages to all possible error scenarios if needed.
- [ ] Define a unified error-handling mechanism. The mechanism should include specific error codes, error messages, and suggested actions to resolve the issue.
- [ ] Define the documentation for the error-catching mechanism, including how users can receive error messages and suggested actions to resolve the issue.
- [ ] Create issues to update the SDK, including the documentation with the new error-handling mechanism.

**Comment by ricardobrg** [comment]
Check how to pass the error to JS
